name: Build
on:
  push:
    branches:
      - master

jobs:

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install-raylib-ubuntu-prerequisites
        run: |
          sudo apt install -y build-essential
          sudo apt install -y git
          sudo apt install -y cmake
          sudo apt install -y libasound2-dev
          sudo apt install -y mesa-common-dev
          sudo apt install -y libx11-dev
          sudo apt install -y libxrandr-dev
          sudo apt install -y libxi-dev
          sudo apt install -y xorg-dev
          sudo apt install -y libgl1-mesa-dev
          sudo apt install -y libglu1-mesa-dev
      - name: install-raylib-ubuntu-build
        run: |
          git clone https://github.com/raysan5/raylib.git raylib
          cd raylib
          mkdir build && cd build
          cmake -DBUILD_SHARED_LIBS=ON ..
          make
          sudo make install
          cd ..
          rm -fr raylib
      - name: build-on-ubuntu
        run: |
          mkdir build
          cd build && cmake ..
          cmake --build .
          cd ..
      - name: print-check-ubuntu
        run: |
          ls -l
          ls -l build

  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: install-raylib-windows-build
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install
          vcpkg install raylib
          cd ..
          Remove-Item -Force -Recurse vcpkg
      - name: build-on-windows
        run: |
          mkdir build
          cd build && cmake ..
          cmake --build .
          cd ..
      - name: print-check-windows
        run: |
          dir
          dir build
