name: Build

on:  
  push:
    branches:
      - master
    paths:
      - "**/CMakeLists.txt"
      - "**/*.hpp"
      - "**/*.cpp"
      - ".github/workflows/*.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**/CMakeLists.txt"
      - "**/*.hpp"
      - "**/*.cpp"
      - ".github/workflows/*.yml"

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:

      - name: install-raylib-ubuntu-prerequisites
        run: |
          sudo apt install -y build-essential \
            git \
            cmake \
            libasound2-dev \
            mesa-common-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            xorg-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev

      - name: install-raylib-ubuntu-build
        run: |
          git clone https://github.com/raysan5/raylib.git raylib
          cd raylib
          mkdir build && cd build
          cmake -DBUILD_SHARED_LIBS=ON ..
          make
          sudo make install
          cd ..
          rm -fr raylib

      - name: install-emscriptensdk-ubuntu-prerequisites
        run: |
          sudo apt install -y git \
            python3 \
            cmake

      - name: install-emscriptensdk-ubuntu-build
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..

      - uses: actions/checkout@v2

      - name: build-desktop-on-ubuntu
        run: |
          mkdir build
          cd build && cmake ..
          cmake --build .
          cd ..

      - name: build-web-on-ubuntu
        run: |
          emcmake cmake -S . -B build -DPLATFORM=Web
          cd build && make
          cd ../..

  build-on-windows:
    runs-on: windows-latest
    steps:

      - name: install-raylib-windows-build
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install
          vcpkg install raylib
          cd ..
          Remove-Item -Force -Recurse vcpkg

      - name: install-emscriptensdk-windows-build
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          emsdk_env.bat
          cd ..

      - uses: actions/checkout@v1

      - name: build-desktop-on-windows
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build .

      - name: check-binary
        shell: bash
        if: matrix.name == 'Linux'
        run: test -f build/bomberman

  to_github:
    needs:
      - build-on-ubuntu
      - build-on-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}
