name: mirror

on:
  push:
    branches: master

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}